### PR TITLE
[MSHARED-988] Remove CP duplicates

### PR DESCRIPTION
**Pull request by cstamas**
Both org.eclipse.aether (old) and org.apache.maven.resolver
lie in same java package `org.eclipse.aether`, these two pulled in cause classpath
conflict. Get rid on old, use new one.

### CODE REVIEW

**Review by slachiewicz — APPROVED** [review]

**Review by michael-o — COMMENTED** [review]
Why not go with 1.6.2 instead of 1.4.2?

**Comment by cstamas** [comment]
> Why not go with 1.6.2 instead of 1.4.2?

Just wanted to make it least disruptive...  but I agree, moving to 1.6.2 is okay to me as well

**Comment by slachiewicz** [comment]
What version of resolver-api artefact will be injected to plugin in different maven versions? I think we have export defined in core so always older/packaged with core artefact would be used, am I wrong?

**Comment by cstamas** [comment]
That's right, version of resolver here is more like "advice" used at runtime (while it DOES sets version used on build time). AFAIK only Maven 3.8.1 will provide 1.6.2, while older Maven releases will provide older resolvers.

**Comment by michael-o** [comment]
> 
> 
> > Why not go with 1.6.2 instead of 1.4.2?
> 
> Just wanted to make it least disruptive... but I agree, moving to 1.6.2 is okay to me as well

OK, leave 1.4.2 for now.

**Comment by cstamas** [comment]
@elharo any opinion on this?

**Review by elharo — APPROVED** [review]

**Pull request closed without merging**
