### PR TITLE
[MSHARED-950] Remove obsolete code and references to Sonatype Aether

### PR DESCRIPTION
**Pull request by slachiewicz**
This change is [Reviewable](https://reviewable.io/reviews/apache/maven-common-artifact-filters/12)

### CODE REVIEW

**Review by elharo — COMMENTED** [review]
This probably warrants a major version bump. It would be good to have a separate issue and fix release in Jira.

**Review by elharo — COMMENTED** [review]
We've never pushed a release that notes these classes are deprecated. We should probably do that before removing them.

**Comment by slachiewicz** [comment]
Yes, classes where deprecated and this is just clean up

**Review by elharo — COMMENTED** [review]
They're only deprecated at head. The current release version does not deprecate them.

**Comment by slachiewicz** [comment]
Main reason of my removan is due to bump minimum required Maven version to 3.1 where aether artifacts where changed

**Review by elharo — COMMENTED** [review]
I think that's already been done. If that's necessary for this, then it will take two releases to make it happen.

**Pull request closed without merging**
